// This file is generated by the md-to-landing pipeline.
// Run /md-to-landing <path/to/file.md> to regenerate.

export default function Landing() {
  return (
    <div className="min-h-screen bg-[#f5f5f4] flex items-center justify-center">
      <p className="text-[#a8a29e] text-sm">
        Run <code className="font-mono bg-[#e7e5e4] px-1.5 py-0.5 rounded text-[#57534e]">/md-to-landing</code> to generate this page.
      </p>
    </div>
  )
}
